#!/bin/bash

RELBUG=1731
GITSTATUS=`git status`

VERSIONSTATUS=`git status -s rpm/version_name`
if [ -z "$VERSIONSTATUS" ]; then
    echo -n "Version name not updated, enter new version name: "
    read readversion

    if [ -z "$readversion" ]; then
        echo "Version name not updated, exit"
        exit 1
    else
        echo -n $readversion > rpm/version_name
    fi
fi


OLDTAG=`git describe --tags 2>/dev/null`

if [ -n "$OLDTAG" ]; then
    NEWTAG=`echo $OLDTAG | awk -f version.awk`
fi

if [ -z "$NEWTAG" ]; then
    echo "No valid tag"
    exit 1
else
    echo "Tagging $NEWTAG / `cat rpm/version_name`"
fi

if [ -n "$GITSTATUS" ]; then
    git status

    echo
    echo
    echo -n "The above changes will be comitted, are you sure? (y/n/v[ersion only]) "

    read -n 1 yesno
    echo

    if [ "$yesno" = "y" ]; then
        git add --all
    elif [ "$yesno" = "v" ]; then
        git add rpm/version_name
    else
        exit
    fi
fi

git commit -m "[version] Bump to $NEWTAG (`cat rpm/version_name`), JB#$RELBUG" || exit 1
git tag $NEWTAG
git push && git push --tags
