#!/bin/sh

ARCH=`grep ^arch= /etc/ssu/ssu.ini | sed 's/^.*=//'`
if [ -z "$ARCH" ]; then
    sed 's/TARGET_CPU/unknown/' /etc/sailfish-release.template > /etc/sailfish-release
    # retry arch detection on next boot
    exit 1
else
    sed "s/TARGET_CPU/$ARCH/" /etc/sailfish-release.template > /etc/sailfish-release
fi
