#!/bin/bash

RET=0

synopsis()
{
    cat <<END
Usage: $0 [--dup]
END
}

usage()
{
    cat <<END
$(synopsis)

With no option given it prints detailed information about current operating
system version.

Options:
    --dup
        Do system upgrade
END
}

case $1 in
    "--dup")
        if [ -x /usr/bin/rnd-dist-upgrade ]; then
            # Developer mode installed - can use rnd-dist-upgrade directly
            /usr/bin/rnd-dist-upgrade
        elif [ $(id -u) == 0 ]; then
            # Developer mode not installed, but running as root - use pkcon
            pkcon refresh
            MODEL=`ssu model -s | tr '[A-Z]' '[a-z]' | sed 's/ /_/g'`
            pkcon upgrade-system jolla-configuration-$MODEL complete
            echo
            echo "REBOOT NOW, unless you need to investigate update issues, or know what "
            echo "you're doing (or both)."
            echo "All bugs you encounter until reboot are features unless you meet one of the"
            echo "criteria from the previous sentence."
        else
            echo
            echo "Enable developer mode to use rnd-dist-upgrade, or run as root."
            echo
        fi
        ;;
    "--verify")
        echo "$0: The '--verify' option has no effect now and will be completely removed in future" >&2
        ;;
    "")
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            echo $PRETTY_NAME
        else
            echo "release file does not exist"
        fi
        ;;
    -h|--help)
        usage
        ;;
    *)
        echo "Invalid option '$1' given" >&2
        synopsis >&2
        RET=1
        ;;
esac

exit $RET
